version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-employee-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: employee_control_system_db
      MYSQL_USER: emp_user
      MYSQL_PASSWORD: emp_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
